version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/data:/var/lib/mysql

  node:
    image: node:10.15
    tty: true
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    depends_on:
      - mysql